baby:
  yoda:
    name: Grogu

greeting.message: Hello Cloud Profile (where profile is determined by the filename) !!!


---
# spring:
#   config:
#     activate:
#       on-profile: another
spring:
  profiles: another
  
baby:
  yoda:
    name: Baby Yoda
