hello:
  message: Hello, all!!!
  
greeting:
  message: Hiya folks!!!!!

logging:
  level:
    org.mongodb.driver: INFO
---
spring:
  config:
    activate:
      on-profile: cloud
# spring:
#   profiles: cloud
  
foo:
  bar: Hello there, Gogs
